### ISSUE TITLE
Best algo for searching products in E commerce site

### ISSUE THREAD

**Issue by abhishek3008** [abhishek3008/Search_products#1]
Apply the best algo to cover all the cases. 
Eg: $products = ['sensor','capacitor','1N4148 Diode set of 5','BC337 NPN general purpose transistor pack of 2','Electrolytic Capacitor 25volts pack of 5', 'IC base 14pin pack of 2'];

1. if I search capacitor of 25V it should display Electrolytic Capacitor 25volts pack of 5 in my results.
2. if I search sensor -> sensors should be displayed

**Comment by andhikaribrahim** [comment]
Hi, since you did not specify what database/language you are using, here's some approach you can use for that:

If your data sets coming from SQL / MySQL / MariaDB, you can simply use:
```sql
# For example, if you have 25V as the keyword
SELECT * 
FROM products
WHERE <your_product_name_column> LIKE '%25V%';

# One of the result(s) set should return `Electrolytic Capacitor 25volts pack of 5`
```

Assuming you're only using array, you can simply use Array `map` function & `regex` to find the specific similar item(s) to your keyword. How to use Array `map` function may differs, depend on the language that you're using. Some links that may you find useful for this case:
- PHP `array_map`: http://docs.php.net/manual/da/function.array-map.php
- Javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
- PHP [preg_match](https://www.php.net/manual/en/function.preg-match.php) for regex & Javascript's [regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

If you want something more powerful for "searching" algorithm, you can try to take a look on [elastic search](https://www.elastic.co/what-is/elasticsearch)

**Comment by andhikaribrahim** [comment]
Can I take this?
